# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Build
        run: go build -v ./...

      - name: Unit test
        run: |
          export GOCOVERDIR=$PWD/cover
          mkdir $GOCOVERDIR
          go test -v ./...

      - name: Coverage report
        run: |
          ls $PWD/cover
          go tool covdata percent -i=$PWD/cover
          go tool covdata textfmt -i=$PWD/cover -o coverage.txt

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
